# OpenAI API Key
OPENAI_API_KEY = "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"

# ElevenLabs (para generación de voz)
ELEVENLABS_API_KEY = "sk_845f89104ee79e8b173b885cb770cc69ce89adc425f0e381"
ELEVENLABS_VOICE_ID = "sAMGuncP1OMSXFyDOzx6"

# Google Sheets credentials (JSON formateado como una sola línea)
GOOGLE_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "textocorrectorele",
  "private_key_id": "d88c8b5327f8c24d1e3deccde717855410a6ba9d",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCpCwFvbwI2nzKm\\n3n7Csql9N5NjoORTjqMYkfK5oIJHAR1awAMUcJhGnbTUvYKaBkc03AOJ8lGjIjSl\\nkOViIsNxuwxkPrcCt5lxho5JBeppkXcyFmvhxdSk3BJGxUNzl4dWrHF1scj9F8lV\\nPoS5A5Z/zmpTez+FL76O3FsCfBwhXzis2HpiLGSyA1VlsbWenBrtPjvV2vBQami/\\nRCgOjYvK+NzR+YG31gsoglNudUjbTjJXayPeGTwfkN7f7DbjF6shMdPEzUErrYSj\\nFFfdCbinjScuuRgsg8WG3606dAJs9hzyoQ6Ju8UVrN+n/fZUEwb7XhxRB9ydnebv\\nRzoIxCm5AgMBAAECggEAA4xDFfMnAT17Iyx1TaHRU9r4QXWNhUFvo+LgTMwVH+di\\nldaE2gd48rZ5pqNpm9D46p+ZhWosE3fy0ezGG7auEnOCEZKNZcWzt0HDN74jit6u\\nOUNmNUFhMqqZyZl3TnRGN2f8I6O9G67Fn3/l6josjPconSLvlNyJK9dtI5K2Rm7/\\n6Aa8XpSOb85V2etgyGDRB0ec3uvhPfHp/dxZ7i8QiS6zbA/saAVCFuwGl1fw7wKy\\nUhSC0SOBrbz++aPIC8jB6Y7bYU7t3qb0wCo4xRfMnNbT8vEv94CR0dH0PgNZn2Qg\\nZ8JjFP8/B1pVdGNP/Cpx8U//8xwJQbimgAH/cl/y2QKBgQDpIHNJDdMlcuKepu6b\\nzpP5LPI+pkQPS2ZNBt6Z4vISVpQLyfrZh2lI3fqwhU6AIAxnFy3KD5p3UH3MVJbQ\\nUNaamDfEJVZNbR94Rpd0Qa1eY98F/kOdk8/2gezNHP3LYdSYDlI9UI8SuF9wEEHm\\nw/X/h67gGWbnWEFukPijaVn0vQKBgQC5oO83Oe8oqMo8DGwOCiyI1ymfeJevo45n\\nI3EKTUt/XUWHpz5//7myWEfjy71Mgl/50i85rI/s3vRqvLL7Q6hSRIecwn1XBWda\\nyS8DMA2WiiKtMJ6gh0s+5PquPhuNWwVEhH9sL1evLp0JGHnT6ttnWIXGqna8LdXG\\ngcMascQ+rQKBgFa95Ud8ZmEbwyinEkdU8QgY6jXXZaGPO4xTjwYRRGMAZeuRBs5j\\nrRAY0EtX/qJ7ykGdhUMW1TGp+HTL0KXIPmGdW7qW7eq3PKtjEL2IJnrljDlNp1j9\\ng7bEFxkmvWQsjY7aXU1FKUcc5R3sXqj/pwuiL7ZgnUJdO1Npi6o56+e9AoGAFhZW\\nIGYeVOIwnhCEUu9W+TlQ1I7OzbFSYmdPLgCgeRkqCsgVoblV6Sij9TDq502kCd++\\nishDn9Wvk3u8eDVGs/M/h6GEtHQKJj1GAMUY+M6a7ayZU1SF2Yf5Y/4z3Q/1gn+Z\\ngc/oSQns2YY2CMcrMBLSaB8kXaO+ig4qnuSEC0kCgYBbkGzcegq/QQleV/vyuVJS\\neGtZ4CHlHDCscvpUIMJJ1T9bAXFQcLwT4zkkKMUEIUQFKY/4ZG3PU0atqmQfwwRm\\nxKHZfAIgG3owe7R2yFf0WXOlGbL4og6soqDn3WUL93N5JwBgLcZYyE4wkEgrtlHI\\nawo4v/t2GZf7a/sf8avYyA==\\n-----END PRIVATE KEY-----\\n",
  "client_email": "textocorrector-service@textocorrectorele.iam.gserviceaccount.com",
  "client_id": "114096453062043904675",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/textocorrector-service%40textocorrectorele.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
